apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret-external
  namespace: demo
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: db-password
